server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
