server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    jwt:
      private-key: ${private-key}
      user-generator: ${user-generator}

